# This file contains values from Cookiecutter

default_context:
  project_name: "pylib_semver"
  project_description: "Awesome `pylib_semver` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "pandalearnstocode"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "pandalearnstocode"
  email: "pandalearnstocode@gmail.com"
  version: "0.0.0"
  line_length: "120"
  create_example_template: "cli"
